# -*- coding: utf-8 -*-
"""Fotran_tutorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17PaMK3X7mtkdWWid0noFP_qvI4El-GfR

# Ejecutar Codigo en jupyter notebooks

Usando fortran en un entorno virtual
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile get_age.f90
# 
# program get_age
#     real :: year, age
#     print *, 'What year were you born?'
#     read *, year
#     age = 2020 - year
#     print *, 'Your age is', age
# end program get_age
#

# Commented out IPython magic to ensure Python compatibility.
# %%script bash
# %%bash
# 
# gfortran -ffree-form get_age.f90
# ./a.out
# 1984